package com.github.monaboiste.shipping.event;

import java.io.Serializable;
import java.time.Instant;

/**
 * Represents an event in the system. Some events may be:
 * <ul>
 * <li>incoming - received from external sources, causing internal state changes or reactions
 * <li>outgoing - generated by the system to communicate with external systems, clients, or other services
 * <li>both incoming and outgoing - some events may exhibit a dual nature, where they are both
 * incoming (triggered by external responses, leading to internal state changes) and outgoing
 * (sent to notify other systems or clients of the result)
 * </ul>
 *
 * @param <P> additional data payload
 */
public interface Event<P extends Payload> extends Serializable {

    /**
     * @return event identifier
     */
    String eventId();

    /**
     * @return the name of the event
     */
    String name();

    /**
     * @return the precise moment we first observed the event
     */
    Instant occurredAt();

    /**
     * @return a serializable payload
     */
    P payload();

    /**
     * @return aggregate identifier
     */
    String aggregateId();

    /**
     * @return the class of this event
     */
    Class<? extends Event<P>> type();
}
